### ISSUE TITLE
tensorboard4.py make log directory name linux compatible

### ISSUE THREAD

**Issue by peter-pri** [franneck94/UdemyTF#2]
in Line 21:
LOGS_DIR = os.path.abspath("C:/Users/jan/OneDrive/_Coding/UdemyTF/logs/")

This works only for Windows.
I change this to:
LOGS_DIR = os.path.abspath("logs/")
to get it working under  Linux.
This applies for all other appearances of logfile directory definitions in the UdemyTF source code.

**Comment by franneck94** [comment]
The logs path must be changed by the user anyway
